CREATE DATABASE DEMO;
USE  DEMO;
CREATE TABLE EMPLOYEE(
ID VARCHAR(10),
dNAME VARCHAR(15),
SALARY INT(6),
AGE INT(3)

 );

INSERT INTO EMPLOYEE VALUES('A12',"RAMU",1200, 23);
INSERT INTO EMPLOYEE VALUES('A13',"SOMU",1900, 23);
INSERT INTO EMPLOYEE VALUES('A14',"KIRAN",20000, 23);
INSERT INTO EMPLOYEE VALUES('A15',"KISHORE",25000, 20);
INSERT INTO EMPLOYEE VALUES('A16',"RAJU",1000, 23);
SELECT *FROM EMPLOYEE;

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
